# Source: https://github.com/flutter/packages/blob/master/packages/flutter_lints/lib/flutter.yaml
# Recommended lints for Flutter apps, packages, and plugins.

include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_single_quotes
    - sized_box_for_whitespace
    - unawaited_futures
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
