name: geiger_api
description: >-
  A Communication API for the GEIGER ecosystem. It provides a unified interface for all plugins to
  communicate and transfer control between the components of the ecosystem.
version: 0.7.0
homepage: https://github.com/cyber-geiger/toolbox-storage
repository: https://github.com/cyber-geiger/toolbox-communicationApi
documentation: https://github.com/cyber-geiger/toolbox-communicationApi/wiki

flutter:
  plugin:
    platforms:
      android:
        package: eu.cybergeiger.communication
        pluginClass: GeigerPlugin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  geiger_localstorage: ^0.6.26
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.5
  collection: ^1.15.0
  android_intent_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_isolate: ^2.0.0
  lints: ^1.0.1
  test: ^1.17.12
