name: communicationapi
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  geiger_localstorage: ^0.6.3
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
