name: geiger_api
description: >-
  A Communication API for the GEIGER ecosystem. It provides a unified interface for all plugins to
  communicate and transfer control between the components of the ecosystem.
version: 0.7.9
homepage: https://github.com/cyber-geiger/toolbox-storage
repository: https://github.com/cyber-geiger/toolbox-communicationApi
documentation: https://github.com/cyber-geiger/toolbox-communicationApi/wiki

flutter:
  plugin:
    platforms:
      android:
        package: eu.cybergeiger.communication
        pluginClass: GeigerPlugin
  #assets:
  #  - packages/geiger_localstorage/lib/assets/store/store.data

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  geiger_localstorage: ^0.6.47
    #path: ../geiger_localstorage
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.6
  collection: ^1.15.0
  cryptography: ^2.0.5
  convert: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_isolate: ^2.0.0
  lints: ^1.0.1
  test: ^1.19.5
