name: geiger_api
description: A Communication API for the GEIGER ecosystem.
version: 0.5.0
repository: https://github.com/cyber-geiger/toolbox-communication
documentation: https://github.com/cyber-geiger/toolbox-communication/wiki

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  geiger_localstorage: ^0.6.4
  meta: ^1.7.0
  uuid: ^3.0.5
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
