name: communicationapi
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  localstorage:
    git:
      url: https://github.com/cyber-geiger/toolbox-storage.git
      ref: chore/dart-migration

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
