name: master_app
description: App with master geiger plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  geiger_api:
    path: ../../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.1
  flutter_test: 
    sdk: flutter
    version: ^0.0.0

flutter:
  uses-material-design: true