name: client_app
description: App with client geiger plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  geiger_api:
    path: ../../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.1

flutter:
  uses-material-design: true
