name: Setup project
description: Setup project
runs:
  using: composite
  steps:
    - name: Install flutter
      uses: subosito/flutter-action@v2
    - name: Print environment
      run: flutter doctor -v
      shell: bash
    - name: Get dependencies
      run: flutter pub get
      shell: bash