name: Base jobs (run unit tests, check linting, check formatting)
on: workflow_call

jobs:
  run-unit-test:
    name: Run unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-18.04, ubuntu-20.04,
          macos-10.15, macos-11,
          windows-2016, windows-2019, windows-2022
        ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: flutter test

  check-lint:
    name: Check lint rule compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: flutter analyze

  check-format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: flutter format --set-exit-if-changed --dry-run .