name: Internal Github Action Flow
on:
  push:
    branches:
      - main
      - development
      - master
    paths:
      - .github/**
      - dart/**
  pull_request:
    paths:
      - .github/**
      - dart/**

jobs:
  base:
    uses: ./.github/workflows/dart-base.yaml

  trigger-extenal:
    name: Trigger external workflows
    runs-on: ubuntu-latest
    needs: base
    steps:
      - name: Trigger external_workflows on toolbox-ui-flutter
        run: |
          curl \
          -X POST \
          -u '${{secrets.GEIGER_USERNAME}}:${{secrets.APPLICATION_ACCESS_TOKEN}}' \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/cyber-geiger/toolbox-ui-flutter/actions/workflows/external_workflow.yaml/dispatches \
          -d '{"ref":"refs/heads/development"}'
      - name: Trigger external_workflows on toolbox-replication
        run: |
          curl \
          -X POST \
          -u '${{secrets.GEIGER_USERNAME}}:${{secrets.APPLICATION_ACCESS_TOKEN}}' \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/cyber-geiger/toolbox-replication/actions/workflows/external_workflow.yaml/dispatches \
          -d '{"ref":"refs/heads/development"}'
      - name: Trigger external_workflows on toolbox-indicator
        run: |
          curl \
          -X POST \
          -u '${{secrets.GEIGER_USERNAME}}:${{secrets.APPLICATION_ACCESS_TOKEN}}' \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/cyber-geiger/toolbox-indicator/actions/workflows/external_workflow.yaml/dispatches \
          -d '{"ref":"refs/heads/development"}'

