name: Internal Github Action Flow
on:
  push:
    branches:
    - main
    - development
    - master
  pull_request:

jobs:
  unit-test:
    name: -> Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, windows-2019, macos-10.15]
        os: [ubuntu-18.04]
    # runs-on: ubuntu-latest
    # container:
    #   image:  google/dart:latest
    steps:
    # Set up Flutter.
    - name: -> Setup Flutter environment
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter doctor -v

    # Checkout gallery code and get packages.
    - name: -> Checkout gallery code
      uses: actions/checkout@v2
    - name: -> Get packages
      run: flutter pub get

    # Analyze, check formatting, and run unit tests.
    - name: -> Analyze the project source code (lints)
      run: flutter analyze
    - name: -> Check the source code format
      run: flutter format --set-exit-if-changed --dry-run .
    # Run the unit tests
    - name: -> Run unit tests
      run: flutter test

    # # publish to pub.dev
    # - name: -> Check before publish to pub.dev
    #   run: dart pub publish --dry-run
    # - name: Setup credentials
    #   run: |
    #     cat <<EOF > $PUB_CACHE/credentials.json
    #     ${{ secrets.PUBDEV_CREDENTIAL }}
    #     EOF
    # - name: -> Publish package
    #   run: dart pub publish -f

    # Trigger other to test the application
    - name: -> Trigger the external_workflows on other repositories
      run: |
          curl \
          -X POST \
          -u '${{secrets.GEIGER_USERNAME}}:${{secrets.APPLICATION_ACCESS_TOKEN}}' \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/cyber-geiger/toolbox-ui-flutter/actions/workflows/external_workflow.yaml/dispatches \
          -d '{"ref":"refs/heads/development"}'

